spring.application.name=gradtrack

jwt.secret=2f8d7c9a4b1e6f0d9c3a8b7e5d1f6a0c
jwt.expiration-ms=86400000
#spring.datasource.url=jdbc:h2:mem:gradtrackdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

#spring.h2.console.enabled=true