package com.gradtrack.model;

public enum ActivityType {

    APPLICATION_CREATED,
    APPLICATION_UPDATED,
    APPLICATION_DELETED,
    STATUS_CHANGED,
    INTERVIEW_CREATED,
    INTERVIEW_UPDATED,
    INTERVIEW_OUTCOME_UPDATED,
    DEADLINE_UPDATED,
    NOTE_UPDATED
}
